runtime: python38

entrypoint: gunicorn -w 2 -b :$PORT main:app

env_variables:
  MONGO_CONNECTION_STRING: "mongodb+srv://arpanqx:arpan77@cluster0.iqoj2fz.mongodb.net/?retryWrites=true&w=majority"
  DB_NAME: "vents"
  COLLECTION_NAME: "01"

handlers:
- url: /.*
  script: auto
  secure: always